name: OnyxHomes
version: '1.0.1'
main: com.timedust.onyxHomes.OnyxHomes
api-version: '1.21'
authors: [ TimeDust42 ]

commands:
  onyxhomes:
    description: "Okay"
  home:
    description: "Okay"
  sethome:
    description: "Okay"
  delhome:
    description: "Okay"